version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "k8s.io/api"
    - dependency-name: "k8s.io/apimachinery"
